codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "0...100"

  status:
    project: yes
    patch: yes
    changes: no

flags:
  # filter the folder(s) you wish to measure by that flag
  src:
    # only include files in the backend folder
    paths:
      - main/java
  tests:
    paths:
      - main/test

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no