version: '3.8'

services:
        fantaleghe-backend:
                image: antpas14/fantaleghe-backend:latest
                ports:
                        - "8080:8080"
        fantaleghe-ui:
                image: fantaleghe-ui-react:latest
                ports:
                        - "3000:80"
                links:
                        - "fantaleghe-backend:fantaleghe-backend"
                depends_on:
                        - fantaleghe-backend

