-- SEQUENCE
CREATE SEQUENCE IF NOT EXISTS RANK_SEQ START 1;
CREATE SEQUENCE IF NOT EXISTS LEAGUE_SEQ START 1;

CREATE TABLE IF NOT EXISTS LEAGUE (
    ID BIGINT PRIMARY KEY,
    LEAGUE_NAME VARCHAR(255),
    LAST_UPDATED DATE
);

CREATE TABLE IF NOT EXISTS RANK (
  ID BIGINT PRIMARY KEY,
  LEAGUE_ID BIGINT REFERENCES LEAGUE(ID),
  POINTS INT,
  EV_POINTS NUMERIC(8,2),
  NAME VARCHAR(255)
);