server:
  port: 8100
  servlet:
    context-path: /
logging:
  level:
    org.springframework.web: DEBUG
properties:
  baseUrl: "http://leghe.fantacalcio.it/"
  calendarSuffix: "/calendario"
  rankingSuffix: "/classifica"
  seleniumUrl: "http://localhost:4444/wd/hub"

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation : false
spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults : false;

props:
  url: jdbc:postgresql://localhost:5432/fantaleghe
  driverClassname: org.postgresql.Driver
  username: fantaleghe
  password: fantaleghe
  hbm2ddlAuto: validate
  packagesToScan: org.gcnc.calculate
  showSql: true
