name: pull_request

on:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up Maven
        env:
          MAVEN_USERNAME: antpas14
          MAVEN_TOKEN: ${{ secrets.MAVEN_PAT }}
        run: |
          echo "Setting up Maven with credentials..."
          MAVEN_TOKEN_FIRST_FOUR=$(echo "${MAVEN_TOKEN}" | cut -c1-4)
          MAVEN_TOKEN_LAST_FOUR=$(echo "${MAVEN_TOKEN}" | rev | cut -c1-4 | rev)
          echo "Partial Maven Token: $MAVEN_TOKEN_FIRST_FOUR****$MAVEN_TOKEN_LAST_FOUR"

          echo "<settings><servers><server><id>github</id><username>\${env.MAVEN_USERNAME}</username><password>\${env.MAVEN_TOKEN}</password></server></servers></settings>" > $HOME/.m2/settings.xml

      - name: Build with Maven
        run: |
          echo $HOME/.m2/settings.xml
          mvn clean install -s $HOME/.m2/settings.xml
      -
        name: Upload to code cov
        uses: codecov/codecov-action@v3
